#!/bin/bash

swift package --allow-writing-to-directory docs \
    generate-documentation \
    --product Calligraphy \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path docs \
    --output-path docs