#!/bin/bash

cat > _config.yml <<EOF
remote_theme: vsanthanam/aviary@v0.1.0
plugins:
- jekyll-remote-theme
documentation_url: "https://www.usecalligraphy.com/docs/documentation/calligraphy"
copyright_owner: "Varun Santhanam"
EOF

echo "✅ _config.yml created."