name: Validate Documentation
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build-docc:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Validate Documentation
      run: ./.scripts/check-docc
