name: Build & Test (SPM)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: swift test -v
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: swift test -v
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Swift
        uses: compnerd/gha-setup-swift@v1
        with:
          swift-version: '6.1' # or your preferred version
      - name: Run Tests
        run: swift test -v
