name: Test (SPM Platforms)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test-macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test
  test-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test
