name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

permissions:
  checks: write
  contents: read

jobs:
  test-macos-spm:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: swift test