name: Validate Release
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-docc-archive:
    runs-on: macos-15
    outputs:
      artifact-name: archive
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.3.app
      - name: Build Documentation
        run: swift package generate-documentation --target Calligraphy
      - name: Compress DocC Archive
        run: zip -r Calligraphy.doccarchive.zip .build/plugins/Swift-DocC/outputs/Calligraphy.doccarchive
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: Calligraphy.doccarchive.zip
  attach-archive:
    needs: build-docc-archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Documentation Archive
        uses: actions/download-artifact@v4
        with:
          name: archive
          path: .
      - name: Attach DocC Archive to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Calligraphy.doccarchive.zip
  launch-publish:
    needs: attach-archive
    runs-on: ubuntu-latest
    steps:
      - name: Request Website Publication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish.yml/dispatches \
            -d "{\"ref\":\"${{ github.event.release.tag_name }}"}}"