name: watchOS 11.4 Build / Test (Xcode 16.3)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -destination "OS=11.4,name=Apple Watch Series 10 (46mm)"
