name: Build (Xcode Platforms)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || 'xcode-build' }}
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build Calligraphy
      run: xcodebuild -scheme Calligraphy -destination 'platform=macOS'
  build-maccatalyst:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build Calligraphy
      run: xcodebuild -scheme Calligraphy -destination 'platform=macOS,variant=Mac Catalyst'
  build-ios:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build Calligraphy
      run: xcodebuild -scheme Calligraphy -sdk iphonesimulator -destination "OS=18.4,name=iPhone 16"
  build-watchos:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build Calligraphy
      run: xcodebuild -scheme Calligraphy -destination "OS=11.4,name=Apple Watch Series 10 (46mm)"
  build-tvos:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build Calligraphy
      run: xcodebuild -scheme Calligraphy -destination "OS=18.4,name=Apple TV 4K (3rd Generation)"
  build-visionos:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Build Calligraphy
      run: xcodebuild -scheme Calligraphy -destination "OS=2.4,name=Apple Vision Pro"
