name: Build & Test (Xcode)
on:
  push:
    branches: [ "main" ]
jobs:
  build-macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -destination 'platform=macOS'
  build-maccatalyst:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -destination 'platform=macOS,variant=Mac Catalyst'
  build-ios:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -sdk iphonesimulator -destination "OS=18.4,name=iPhone 16"
  build-watchos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -destination "OS=11.4,name=Apple Watch Series 10 (46mm)"
  build-tvos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -destination "OS=18.4,name=Apple TV 4K (3rd Generation)"
  build-visionos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.3.app
    - name: Run Tests
      run: xcodebuild test -scheme Calligraphy -destination "OS=2.4,name=Apple Vision Pro"
